OperationsCenter:
  # Set the HostName for the Operation Center
  HostName: 'cbci.dbschott.com' 
  # Setting ServiceType to ClusterIP creates ingress
  ServiceType: ClusterIP
  Ingress:
    tls:
    ## Set this to true in order to enable TLS on the ingress record
      Enable: false 
      # Create a certificate and use it here.
      SecretName: cbci-dbschott-com-tls
      Host: jenkins.cluster.local
